### ISSUE TITLE
Pro-tables i18n showing buttong in chinese🐛[BUG]

### ISSUE THREAD

**Issue by arpanEnbake** [ant-design/ant-design-pro#7377]
### 🐛 bug 
Go to https://preview.pro.ant.design/list/table-list
Change language to English from top right
The buttons and tool tip still remain in Chinese

If we go to codeblock example of pro table and use version 3.6.1, this works fine in stand alone
This issue only comes when we add this in ant design pro project
works fine for : https://codesandbox.io/s/pro-table-forked-d73p5?file=/src/index.tsx

`    <IntlProvider value={enUSIntl}>
    <ProTable />
`

### 💻 

- Ant Design Pro : alha-5.0
macOS
windows
linux

**Comment by xuemingdg** [comment]
The latest code should have fixed this. I just tried removing my node_modules and re-install it. The issue is solved.

**Comment by arpanEnbake** [comment]
@xuemingdg I tried that but issue is still there.

It works if I check in stackblitz but does not work when we integrate in pro.

Any help would be appreciated
![Uploading Screenshot 2020-09-22 at 11.16.54 PM.png…]()

**Comment by arpanEnbake** [comment]
Closing this issue. Its not coming with latest pro v5. Will be moving project to new version.
